; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{40CDF056-0B9B-41CF-A798-FA02184E15F3}
AppName=LachanceC
AppVersion=1.0
;AppVerName=LachanceC 1.0
AppPublisher=LachanceCsoft Inc.
AppPublisherURL=http://www.lachancecsoft.com/
AppSupportURL=http://www.lachancecsoft.com/
AppUpdatesURL=http://www.lachancecsoft.com/
DefaultDirName={autopf}\LachanceC 1.0 de LachanceCsoft inc.
DefaultGroupName=LachanceC 1.0
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Lachance-C\Installation
OutputBaseFilename=LachanceCsetup
SetupIconFile=C:\Lachance-C\Application\PUTTY.ico
Password=ayoye
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Lachance-C\Application\PUTTY.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PAGEANT.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PLINK.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PSCP.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PSFTP.EXE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PUTTY.CHM"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PUTTY.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Lachance-C\Application\PUTTYGEN.EXE"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\LachanceC"; Filename: "{app}\PUTTY.EXE"
Name: "{group}\{cm:ProgramOnTheWeb,LachanceC}"; Filename: "http://www.lachancecsoft.com/"
Name: "{group}\{cm:UninstallProgram,LachanceC}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\LachanceC"; Filename: "{app}\PUTTY.EXE"; Tasks: desktopicon

[Run]
Filename: "{app}\PUTTY.EXE"; Description: "{cm:LaunchProgram,LachanceC}"; Flags: nowait postinstall skipifsilent

