; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Christophe Lachance, 2 mars 2020
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{40CDF056-0B9B-41CF-A798-FA02184E15F3}
AppName=LachanceC
AppVersion=1.0
;AppVerName=LachanceC 1.0
AppPublisher=LachanceCsoft Inc.
AppPublisherURL=http://www.lachancecsoft.com/
AppSupportURL=http://www.lachancecsoft.com/
AppUpdatesURL=http://www.lachancecsoft.com/
DefaultDirName={autopf}\LachanceC 1.0 de LachanceCsoft inc.
DefaultGroupName=LachanceC 1.0
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Lachance-C\Installation
OutputBaseFilename=LachanceCsetup
SetupIconFile=C:\Lachance-C\Application\PUTTY.ico
Password=ayoye
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Components]
Name: "lachancec"; Description: "Application LachanceC"; Types: full compact custom; Flags: fixed ; ExtraDiskSpaceRequired: 4860527
Name: "user"; Description: "User's guide"; Types: full ; Languages: english
Name: "usager"; Description: "Guide de l'usager"; Types: full ; Languages: french
Name: "readme"; Description: "Readme file"; Types: full ; Languages: english
Name: "lisezmoi"; Description: "Fichier Lisez-moi"; Types: full ; Languages: french

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl" ; LicenseFile: "C:\Lachance-C\Application\Licences\LicenseEN.rtf"
Name: "french"; MessagesFile: "compiler:Languages\French.isl" ; LicenseFile: "C:\Lachance-C\Application\Licences\LicenseEN.rtf"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checked

[Files]
Source: "C:\Lachance-C\Application\PUTTY.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PAGEANT.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PLINK.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PSCP.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PSFTP.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PUTTY.CHM"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PUTTY.ico"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\PUTTYGEN.EXE"; DestDir: "{app}"; Flags: ignoreversion ; Components: lachancec
Source: "C:\Lachance-C\Application\Guides\User guide.pdf"; DestDir: "{app}/User's guide"; Flags: ignoreversion ; Components: user
Source: "C:\Lachance-C\Application\Guides\Guide usager.pdf"; DestDir: "{app}/Guide de l'usager"; Flags: ignoreversion ; Components: usager
Source: "C:\Lachance-C\Application\Readmes\Readme.txt"; DestDir: "{app}/Readme file"; Flags: ignoreversion ; Components: readme
Source: "C:\Lachance-C\Application\Readmes\Lisez-moi.txt"; DestDir: "{app}/Fichier Lisez-moi"; Flags: ignoreversion ; Components: lisezmoi

[Icons]
Name: "{group}\LachanceC"; Filename: "{app}\PUTTY.EXE" ; IconFilename: "{app}\PUTTY.ico"
Name: "{group}\{cm:ProgramOnTheWeb,LachanceC}"; Filename: "http://www.lachancecsoft.com/" ; IconFilename: "C:\Lachance-C\Installation\www.ico"
Name: "{group}\{cm:UninstallProgram,LachanceC}"; Filename: "{uninstallexe}" ; IconFilename: "C:\Lachance-C\Installation\uninstall.ico"
Name: "{autodesktop}\LachanceC"; Filename: "{app}\PUTTY.EXE"; Tasks: desktopicon ; IconFilename: "{app}\PUTTY.ico"

[Registry]
Root: HKLM; Subkey: "Software\LachanceC"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\LachanceC"; ValueType: string; ValueName: "Langue"; ValueData: "{language}"
Root: HKLM; Subkey: "Software\LachanceC"; ValueType: dword; ValueName: "Numéro"; ValueData: "1"

[Run]
Filename: "{app}\Readme file\Readme.txt"; Description: "See README file"; Flags: postinstall shellexec skipifsilent waituntilterminated ; Languages: english ; Components: readme
Filename: "{app}\Fichier Lisez-moi\Lisez-moi.txt"; Description: "Voir le fichier Lisez-Moi"; Flags: postinstall shellexec skipifsilent waituntilterminated ; Languages: french ; Components: lisezmoi
Filename: "{app}\PUTTY.EXE"; Description: "{cm:LaunchProgram,LachanceC}"; Flags: nowait postinstall skipifsilent